// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYPS01uMId-PMsJ0i8LRtE-ysgma_Oqdg',
    appId: '1:172279094373:web:01dae5b8e6be1175d4fa8c',
    messagingSenderId: '172279094373',
    projectId: 'musicislife-naspace',
    authDomain: 'musicislife-naspace.firebaseapp.com',
    storageBucket: 'musicislife-naspace.appspot.com',
    measurementId: 'G-HJS0Q1TGC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJsu9YAeER8PWGO7MjUdOt4Dpl9OmgcCw',
    appId: '1:172279094373:android:6a9e87183f4c806dd4fa8c',
    messagingSenderId: '172279094373',
    projectId: 'musicislife-naspace',
    storageBucket: 'musicislife-naspace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACra5dmwe4OROLbOjiMqOXp0VjVwTyM5M',
    appId: '1:172279094373:ios:d4b62255a1e09be6d4fa8c',
    messagingSenderId: '172279094373',
    projectId: 'musicislife-naspace',
    storageBucket: 'musicislife-naspace.appspot.com',
    iosClientId: '172279094373-moit0d0520giupnr0mbq7an2v0u6tbmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.naspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACra5dmwe4OROLbOjiMqOXp0VjVwTyM5M',
    appId: '1:172279094373:ios:fdb2ffbb639980ffd4fa8c',
    messagingSenderId: '172279094373',
    projectId: 'musicislife-naspace',
    storageBucket: 'musicislife-naspace.appspot.com',
    iosClientId: '172279094373-1287goi5295kk949iqfo0lqblqiq5pgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.naspace.RunnerTests',
  );
}
